name: Sovereign Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: Peter-Free/buildozer-action@v1
        with:
          command: buildozer -v android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Sovereign-S1100-APK
          path: bin/*.apk
